name: EMFAddons
version: '${version}'
main: dev.jsinco.emfaddons.EMFAddons
api-version: '1.20'
depend: [EvenMoreFish]
softdepend: [LuckPerms]
commands:
  emfaddons:
    description: EMFAddons command
    permission: emfaddons.command
    usage: /<command>
  notifynewfishrecord:
    description: Notify new fish record
    usage: /<command>
    aliases: [fn]
  fs:
    description: Fish top command alias
    usage: /<command>
  sf:
    description: Fish shop command alias
    usage: /<command>